apiVersion: apps/v1
kind: Deployment
metadata:
  name: battleforcastile-auth-deployment
  labels:
    name: battleforcastile-auth
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: battleforcastile-auth
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: battleforcastile-auth
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: battleforcastile-auth-cloudsql-instance-credentials
          secret:
            secretName: battleforcastile-auth-cloudsql-instance-credentials
      containers:
        - name: battleforcastile-auth
          image: "{{ .Values.image_battleforcastile_auth.repository }}:{{ .Values.image_battleforcastile_auth.tag }}"
          imagePullPolicy: {{ .Values.image_battleforcastile_auth.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image_battleforcastile_auth.container_port }}
              protocol: TCP
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: battleforcastile-auth-secrets
                  key: secret_key
            - name: SQLALCHEMY_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: battleforcastile-auth-secrets
                  key: sqlalchemy_database_uri
            # - name: PRODUCTION_MODE
            #   value: "false"
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
